export const ADVERTISEMENT_TITLE_MAX_LENGTH = 256
export const ADVERTISEMENT_DESCRIPTION_MAX_LENGTH = 2048
export const ADVERTISEMENT_ITEM_DESCRIPTION_MAX_LENGTH = 512

export const ADVERTISER_NOTE_MAX_LENGTH = 512
export const RESPONDER_NOTE_MAX_LENGTH = 512
export const RESPONSE_ITEM_DESCRIPTION_MAX_LENGTH = 512


