version: '2'
services:
  egidio-backend:
    build:
      context: ./backend
    environment:
      - EGIDIO_EMAIL_USERNAME
      - EGIDIO_EMAIL_PASSWORD
      - EGIDIO_EMAIL_HOST
      - EGIDIO_EMAIL_PORT
      - EGIDIO_EMAIL_PROTOCOL
      - EGIDIO_DATASOURCE_PASSWORD
      - EGIDIO_DATASOURCE_URL
      - EGIDIO_DATASOURCE_USERNAME
      - EGIDIO_BACKEND_PORT=80
      - EGIDIO_FRONTEND_URL
  egidio-database:
    image: postgres
    restart: always
    volumes:
      - ${EGIDIO_POSTGRES_VOLUME_MOUNT_POINT}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${EGIDIO_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${EGIDIO_DATASOURCE_PASSWORD}
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"
  egidio-frontend:
    build:
      context: ./frontend
      args:
        EGIDIO_FE_ENVIRONMENT: "${EGIDIO_FE_ENVIRONMENT:-production}"
    environment:
      - BUILDKIT_PROGRESS="plain"
  egidio-proxy:
    build: ./proxy
    ports:
      - "80:80"