version: '2'
services:
  backend:
    build:
      context: ./backend
    environment:
      - EGIDIO_EMAIL_USERNAME
      - EGIDIO_EMAIL_PASSWORD
      - EGIDIO_EMAIL_HOST
      - EGIDIO_EMAIL_PORT
      - EGIDIO_EMAIL_PROTOCOL
      - EGIDIO_DATASOURCE_PASSWORD
      - EGIDIO_DATASOURCE_URL
      - EGIDIO_DATASOURCE_USERNAME
    ports:
      - "8080:8080"
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${EGIDIO_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${EGIDIO_DATASOURCE_PASSWORD}
    ports:
      - "5433:5432"